/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LoadLibraryTest */

#ifndef _Included_LoadLibraryTest
#define _Included_LoadLibraryTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LoadLibraryTest
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_LoadLibraryTest_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
